libgeneric-pc: fix possible linker error
undefined reference to symbol 'aio_error@@GLIBC_2.2.5'
.../x86_64-linux-gnu/librt.so: error adding symbols: DSO missing ...